name: fhir_r5
description: FHIR library for supporing the R5 Version of FHIR for Dart & Flutter.
version: 0.1.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r5

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  collection: ^1.19.0
  crypto: ^3.0.3
  fhir_primitives:
    path: ../fhir_primitives
  freezed_annotation: ^2.4.2
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  http: ^1.2.1
  http_parser: ^4.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  mime: ^1.0.5
  oauth2: ^2.0.2
  petitparser: ^6.0.2
  rxdart: ^0.28.0
  ucum: ^0.5.0
  universal_io: ^2.2.2
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.4
  json_serializable: ^6.8.0
  test: ^1.25.8
  mockito: ^5.4.4

dependency_overrides:
  meta: ^1.12.0
  collection: ^1.19.0

