name: fhir_r5_db
description: Lightweight FHIR Db written in Hive so it can run on all platforms.
version: 0.4.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_r5

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.0
  crypto: ^3.0.6
  # fhir_r5: ^0.4.2
  fhir_r5:
    path: ../fhir_r5
  hive_ce: ^2.10.1
  rxdart: ^0.28.0

dev_dependencies:
  test: ^1.25.15
