// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwprrRoeTtpGXIbnAy9BJZbxamsI6NL24',
    appId: '1:691103016946:android:a225802800c58401cf6d6b',
    messagingSenderId: '691103016946',
    projectId: 'demos-322021',
    storageBucket: 'demos-322021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcz5Mfni46qT7cFS0Ws9MgduYNSlC8jzU',
    appId: '1:691103016946:ios:a1c3cdd168d26a6ccf6d6b',
    messagingSenderId: '691103016946',
    projectId: 'demos-322021',
    storageBucket: 'demos-322021.appspot.com',
    androidClientId: '691103016946-8svfcc1soc80dcibqn182uj5l8tu68t5.apps.googleusercontent.com',
    iosClientId: '691103016946-hqo26cgs4gfg0i7549ivj50vr7d09fgb.apps.googleusercontent.com',
    iosBundleId: 'dev.fhirfli.deviceauthdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcz5Mfni46qT7cFS0Ws9MgduYNSlC8jzU',
    appId: '1:691103016946:ios:a1c3cdd168d26a6ccf6d6b',
    messagingSenderId: '691103016946',
    projectId: 'demos-322021',
    storageBucket: 'demos-322021.appspot.com',
    androidClientId: '691103016946-8svfcc1soc80dcibqn182uj5l8tu68t5.apps.googleusercontent.com',
    iosClientId: '691103016946-hqo26cgs4gfg0i7549ivj50vr7d09fgb.apps.googleusercontent.com',
    iosBundleId: 'dev.fhirfli.deviceauthdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdhWphzYxbRkQwVb92K6LPVGgg2DJ-hp0',
    appId: '1:691103016946:web:05319c109d4f605acf6d6b',
    messagingSenderId: '691103016946',
    projectId: 'demos-322021',
    authDomain: 'demos-322021.firebaseapp.com',
    storageBucket: 'demos-322021.appspot.com',
  );

}